/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TransactionSource = IDL.Variant({
  'presentbin' : IDL.Null,
  'manual' : IDL.Null,
});
export const ExpenseRecord = IDL.Record({
  'id' : IDL.Nat32,
  'source' : TransactionSource,
  'note' : IDL.Text,
  'currency' : IDL.Text,
  'createdTimestamp' : Time,
  'category' : IDL.Text,
  'transactionDateTime' : Time,
  'amount' : IDL.Nat32,
});
export const PresentbinTransaction = IDL.Record({
  'note' : IDL.Text,
  'currency' : IDL.Text,
  'fingerprint' : IDL.Text,
  'category' : IDL.Text,
  'transactionDateTime' : Time,
  'amount' : IDL.Nat32,
});
export const ImportSummary = IDL.Record({
  'imported' : IDL.Nat,
  'skippedDuplicates' : IDL.Nat,
  'failed' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpenseRecord' : IDL.Func(
      [IDL.Nat32, IDL.Text, IDL.Text, IDL.Text, Time],
      [IDL.Nat32],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpenseRecord' : IDL.Func([IDL.Nat32], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importPresentbinTransactions' : IDL.Func(
      [IDL.Vec(PresentbinTransaction)],
      [ImportSummary],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExpenseRecord' : IDL.Func(
      [IDL.Nat32, IDL.Nat32, IDL.Text, IDL.Text, IDL.Text, Time],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TransactionSource = IDL.Variant({
    'presentbin' : IDL.Null,
    'manual' : IDL.Null,
  });
  const ExpenseRecord = IDL.Record({
    'id' : IDL.Nat32,
    'source' : TransactionSource,
    'note' : IDL.Text,
    'currency' : IDL.Text,
    'createdTimestamp' : Time,
    'category' : IDL.Text,
    'transactionDateTime' : Time,
    'amount' : IDL.Nat32,
  });
  const PresentbinTransaction = IDL.Record({
    'note' : IDL.Text,
    'currency' : IDL.Text,
    'fingerprint' : IDL.Text,
    'category' : IDL.Text,
    'transactionDateTime' : Time,
    'amount' : IDL.Nat32,
  });
  const ImportSummary = IDL.Record({
    'imported' : IDL.Nat,
    'skippedDuplicates' : IDL.Nat,
    'failed' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpenseRecord' : IDL.Func(
        [IDL.Nat32, IDL.Text, IDL.Text, IDL.Text, Time],
        [IDL.Nat32],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpenseRecord' : IDL.Func([IDL.Nat32], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importPresentbinTransactions' : IDL.Func(
        [IDL.Vec(PresentbinTransaction)],
        [ImportSummary],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExpenseRecord' : IDL.Func(
        [IDL.Nat32, IDL.Nat32, IDL.Text, IDL.Text, IDL.Text, Time],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };