/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExpenseRecord {
  'id' : number,
  'source' : TransactionSource,
  'note' : string,
  'currency' : string,
  'createdTimestamp' : Time,
  'category' : string,
  'transactionDateTime' : Time,
  'amount' : number,
}
export interface ImportSummary {
  'imported' : bigint,
  'skippedDuplicates' : bigint,
  'failed' : bigint,
}
export interface PresentbinTransaction {
  'note' : string,
  'currency' : string,
  'fingerprint' : string,
  'category' : string,
  'transactionDateTime' : Time,
  'amount' : number,
}
export type Time = bigint;
export type TransactionSource = { 'presentbin' : null } |
  { 'manual' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpenseRecord' : ActorMethod<
    [number, string, string, string, Time],
    number
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpenseRecord' : ActorMethod<[number], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenseRecords' : ActorMethod<[], Array<ExpenseRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importPresentbinTransactions' : ActorMethod<
    [Array<PresentbinTransaction>],
    ImportSummary
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateExpenseRecord' : ActorMethod<
    [number, number, string, string, string, Time],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];